store:
    availabilities:
        - German
        - International
    default_locale: de_DE
    localizations:
        - de_DE
        - en_GB
    categories:
        - Versand
    type: extension
    icon: src/Resources/store/icon.png
    automatic_bugfix_version_compatibility: true
    description:
        de: |
            <p><strong>ADDRESSFACTORY DIRECT</strong> von Deutsche Post Direkt, einer auf Adress- und Datenmanagement spezialisierte 100%-Tochter von Deutsche Post DHL Group.
            Der Service bietet hocheffiziente Unterstützung bei der Validierung und Korrektur von Versandadressdaten.</p>
            <p>Dieses Modul integriert den ADDRESSFACTORY DIRECT Service in Ihren Shopware 6 Shop und ermöglicht es Ihnen die Kundenlieferadressen in Deutschland vor dem Versand der Bestellung zu validieren.
            Nach dem eine Bestellung eingegangen ist, können Sie manuell oder automatisch die Lieferadressen überprüfen lassen.
            Die Adressdaten werden validiert und, falls nötig, bezüglich Schreibweise und Plausibilität (Straßenname, Postleitzahl, Stadt) korrigiert.
            Weiterhin wird die Wahrscheinlichkeit einer erfolgreichen Lieferung angezeigt.</p>
            <p>Die Grundlage für diesen Prozess stellt die Postreferenz-Datenbank von Deutsche Post Direkt. Sie ist in Deutschland einzigartig hinsichtlich Größe, Aktualität und Vollständigkeit.
            Die Postreferenz-Datenbank umfasst rund 220 Millionen Privatadressen, davon mehr als 77 Millionen aktive Empfänger, die korrekte Schreibweise von Vor- und Nachnamen und Informationen zu Zustellbarkeit/Unzustellbarkeit.</p>
            <h2>Account &amp; Preisgestaltung</h2>
            <p>Ein zusätzlicher Account wird benötigt und zusätzliche Gebühren fallen an.
            Der benötigte Account wird nicht während der Installation des Plugins angelegt.
            Falls Sie bisher keinen Account besitzen oder Ihr Account nicht für ADDRESSFACTORY DIRECT aktiviert ist, kontaktieren Sie bitte Deutsche Post Direkt.</p>
            <p>Die Deutsche Post Direkt erhält zusätzlich eine Mitteilung, sobald Sie das Plugin herunterladen.</p>
        en: |
            <p><strong>ADDRESSFACTORY DIRECT</strong> is a service of Deutsche Post Direkt, a 100% subsidiary of the world’s leading mail and logistics company Deutsche Post DHL Group, which specialized in address and data management.
            The service offers highly effective assistance in validating and correcting shipment address data.</p>
            <p>This module integrates the ADDRESSFACTORY DIRECT service into Shopware 6 and enables you to check the customer’s delivery address in Germany before shipping the order.
            After an order has been placed, you can manually or automatically check the destination address.
            The information will be validated and, if necessary, corrected regarding spelling and plausibility (street, zip code, city).
            Furthermore, the probability of successful delivery is shown.</p>
            <p>The basis for this process is the postal reference database from Deutsche Post Direkt.
            This database is unique in Germany and contains around 210 million current and former private addresses for validating purposes.</p>
            <h2>Account &amp; Pricing</h2>
            <p>An additional account is required, and additional fees apply.
            The account is not created during extension installation.
            If you do not have an account yet or your account is not activated for ADDRESSFACTORY DIRECT, please contact Deutsche Post Direkt.</p>
            <p>Deutsche Post Direkt will also receive a message when you download the plugin.</p>
    installation_manual:
        de: |
            <p>Folgen Sie der offiziellen Shopware 6 Anleitung zur Plugin Installation: 
            <a href="https://docs.shopware.com/de/shopware-6-de/Erweiterungen/MeineErweiterungen"
            target="_blank">https://docs.shopware.com/de/shopware-6-de/Erweiterungen/MeineErweiterungen</a></p>
        en: |
            <p>Follow the official Shopware 6 guide to install the plugin: 
            <a href="https://docs.shopware.com/en/shopware-6-en/extensions/myextensions"
            target="_blank">https://docs.shopware.com/en/shopware-6-en/extensions/myextensions</a></p>
    tags:
        de:
            - adresse
        en:
            - address
    videos:
        de: []
        en: []
    highlights:
        de:
            - Verbessern Sie die Qualität ihrer internen Datenbank durch korrekte Adressen
            - Vermeiden Sie Rücksendungen durch ungültige Adressen oder nicht zustellbare Lieferungen
            - Erhöhen Sie die Kundenzufriedenheit durch Sicherstellung einer schnellen Lieferung
            - Referenzadressdaten basieren auf den original Leitdaten der Deutschen Post
            - Kompatibel mit der DHL Leitcodierung
        en:
            - Improve the quality of your internal database by having correct addresses
            - Avoid returns caused by invalid addresses or non-deliverable shipments
            - Increase customer satisfaction by ensuring quick delivery
            - Reference address data is based on the original postal routing data of Deutsche Post
            - Compatible with DHL routing codes
    features:
        de:
            - Validierung und Korrektor von Straßenname, Postleitzahl und Stadtnamen
            - Korrektur des Empfängernamens
            - Personenbasierte, haushaltsbasierte oder gebäudebasierte Validierung von Versandinformationen
            - Kennzeichne Bestellungen als "Zustellbar" oder "Nicht Zustellbar"
            - Überprüfen Sie einzelne Adressen manuell oder nutzen Sie einen automatisierten Prozess, um alle eingehenden Bestellungen zu überprüfen
            - Einfache Konfiguration der API mit Zugangsdaten
            - Optionales Logging, um die Fehlersuche zu unterstützen
        en:
            - Validation and correction of street names, zip codes, and city names
            - Correction of receiver names
            - Person-based, household-based, or building-based validation of shipping information
            - Mark shipments as “deliverable” or “non-deliverable”
            - Check single addresses manually, or use an automated process to check all incoming orders
            - Simple API configuration with user credentials
            - Optional logging to assist troubleshooting
    faq:
        de: []
        en: []
    images:
        - file: src/Resources/store/01-preview.jpg
          activate:
            de: true
            en: true
          preview:
            de: true
            en: true
          priority: 0
        - file: src/Resources/store/02-config.png
          activate:
            de: true
            en: true
          preview:
            de: false
            en: false
          priority: 0
        - file: src/Resources/store/03-order-list.png
          activate:
            de: true
            en: true
          preview:
            de: false
            en: false
          priority: 0
        - file: src/Resources/store/04-order-detail.png
          activate:
            de: true
            en: true
          preview:
            de: false
            en: false
          priority: 0
        - file: src/Resources/store/05-order-detail.png
          activate:
            de: true
            en: true
          preview:
            de: false
            en: false
          priority: 0
build:
    extraBundles: []
    shopwareVersionConstraint: ""
    zip:
        composer:
            enabled: false
            before_hooks: []
            after_hooks: []
            excluded_packages: []
        assets:
            enabled: false
            before_hooks: []
            after_hooks: []
            enable_es_build_for_admin: true
            enable_es_build_for_storefront: true
        pack:
            excludes:
                paths: []
            before_hooks: []
changelog:
    enabled: false
    pattern: ""
    template: ""
    variables: {}
    ai_enabled: false
    vcsurl: ""
