const NOT_ANALYSED = 'not_analysed';
const PENDING = 'pending';
const UNDELIVERABLE = 'undeliverable';
const CORRECTION_REQUIRED = 'correction_required';
const POSSIBLY_DELIVERABLE = 'possibly_deliverable';
const DELIVERABLE = 'deliverable';
const ADDRESS_CORRECTED = 'address_corrected';
const ANALYSIS_FAILED = 'analysis_failed';

export default {
    NOT_ANALYSED: NOT_ANALYSED,
    PENDING: PENDING,
    UNDELIVERABLE: UNDELIVERABLE,
    CORRECTION_REQUIRED: CORRECTION_REQUIRED,
    POSSIBLY_DELIVERABLE: POSSIBLY_DELIVERABLE,
    DELIVERABLE: DELIVERABLE,
    ADDRESS_CORRECTED: ADDRESS_CORRECTED,
    ANALYSIS_FAILED: ANALYSIS_FAILED,
};
